project:
  type: manuscript
  output-dir: docs

manuscript:
  article: lab_5.qmd

format:
  html:
    self-contained: true
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true



